app/data_preparation/SQL/buildings_residential.sql
app/data_preparation/SQL/pois.sql
app/database_functions/isochrones.sql

Only buildings that overlap more than 50% with non-residential land-use are added to the list of non-residential buildings.
Also contains two more small bugfixes.

Fix buildingsresidential

---

app/front_end/js/data_preparation.js

When accessibility index is calculated a new key is added on Thematic Data object like "Default_1_json", which contains calculation accessibility indexes. 
The error was on the Isochrone Pois Time update which considers all thematic data properties the same. 
A loop break is added to avoid this error.

Fixed accessibility index bug

---

.gitignore
.travis.yml
Makefile
k8s/config
k8s/postgres.tpl.yaml

- Configure TravisCI to have access to K8s over Kubectl.
- Deploy `porstgres` on K8s with DigitalOcean volume claims (for persistency).

Postgres on K8s deployed using TravisCI

---

_docs/quick_start_docker.md

the "h" of "https" was missing in one link

corrected typo in quick_start_docker

---

app/database/database_functions/heatmap/precalculate_grid.sql

A union is created from the tables called edges_multi_extrapolated and edges_multi (these come from the new pgrouting_edges_multi function).
From this union, the temporary tables are created, which the closest_pois function uses in the end to write reached pois into grid_500.

precalculate_grid now uses the new pgrouting_edges_multi function.

---

app/database/data_preparation/SQL/network_preparation1.sql

Improve 'lit' classification of paths ISSUE#931 lit_classified = 'yes' only if min. 30% of the path needs to intersect with a street lamp buffer

lit_classified > 30% - yes

---

README.md

Hi,
I thought that it would be useful to include the link to the technical documentation of GOAT.

Insert link to GOAT technical documentation

---

app/api/src/db/models/layer_library.py
app/api/src/endpoints/v1/api.py
app/api/src/endpoints/v1/layer_library.py

There is an error:
`sqlalchemy.exc.MissingGreenlet: greenlet_spawn has not been called; can't call await_() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)`
When we try to list layer libraries through the endpoint:
`api/v1/layers/library`

Layer library endpoint

---

app/api/src/core/isochrone.py
app/api/src/crud/crud_isochrone.py
app/api/src/utils.py

- :warning: removed the njit compiler at utils.py@line355.
- if we have the decorator, it will get numba error
Related issue: #1353

[FIX] grid_data types at isochrone.py

---

app/api/src/schemas/geostore.py

+ [FIX] remove empty configurations before saving to database
+ [FIX] check if configuration keys are subset instead of equality to example payload configurations.
Manually tested with:
- No configuration
- Empty keys
- Extra configuration keys
#1430

Fix geostore configuration empty keys

---

app/api/src/core/config.py
app/api/src/db/sql/functions/helper/coordinate_to_pixel.sql
app/api/src/db/sql/init_sql.py
app/api/src/db/sql/triggers/trigger_insert_way_modified.sql
app/api/src/db/sql/triggers/trigger_update_way_modified.sql
app/api/src/db/sql/utils.py

Up/Downgrade methods for database functions/triggers
First of all sort functions by dependencies. This sort also uses in downgrade but it is reversed.
Then, set the schema again (In fact replacing the schema) according to configurations. So we wont have functions in other schemas by accidentally set other schema or not set (So prevent adding to public).
Then have upgrade/downgrade for triggers/functions
Used for migrating the project.
Tested by manually running the upgrade/downgrade
:warning:  upgrade/downgrade of triggers failed.
closes #1368

Rewrite database functions

---

app/api/src/endpoints/v1/api.py
app/api/src/endpoints/v1/opportunities.py
app/api/src/endpoints/v1/opportunity_config.py
app/api/src/schemas/__init__.py
app/api/src/schemas/opportunity_config.py
app/api/src/tests/api/api_v1/test_opportunities.py
app/api/src/tests/api/api_v1/test_opportunity_config.py
app/api/src/tests/utils/opportunity_config.py

Endpoints for:
- List Opportunities
- List Opportunity Groups
- CRUD OpportunityStudyAreaConfig
Endpoints:
Used in Dashboard to config study areas
:warning: Not tested yet
#1421

Add endpoints for Opportunity Study Area Configs

---

app/api/src/crud/crud_static_layer.py
app/api/src/endpoints/v1/static_layers_extra.py
app/api/src/utils.py

pick unique name by trailing sequences if table name already exists
- table name like: file_name -> file_name_1 -> file_name_2
#1427

[FEAT] static layers extra tables unique names

---

app/api/src/crud/base.py
app/api/src/crud/crud_scenario.py
app/api/src/endpoints/v1/geostores.py
app/api/src/endpoints/v1/layer_library.py
app/api/src/endpoints/v1/scenarios.py
app/api/src/endpoints/v1/static_layers_extra.py
app/api/src/endpoints/v1/users.py
app/api/src/tests/api/api_v1/test_geostores.py
app/api/src/tests/api/api_v1/test_layer_library.py
app/api/src/tests/api/api_v1/test_scenarios.py
app/api/src/tests/api/api_v1/test_static_layers_extra.py
app/api/src/tests/api/api_v1/test_users.py
app/api/src/tests/utils/utils.py

Refactor endpoints to accept more than one object to delete
:warning: This will change the functionality and form of endpoints. As we need to pass list of parameters. Previously the parameter could pass as URL part. But now they pass differently (Query params)
Example: `/geostores/?id=1&id=2&id=3`
Endpoints:
#1438

Delete multi endpoints

---

app/client/src/components/isochrones/IsochroneThematicData.vue

- #### Fixed Isochrone position reset after dragging it
- #### Fixed Isochrone result window size ( not scrollable now )
----
- ### Resizeable window ≠
- Due to the druggability feature of the isochrone result window, making it resizable will be such a bug candidate In different browsers and user types of browsers.
----
#1476

Fix Isochrone result window bugs

---

app/api/src/crud/base.py
app/api/src/endpoints/v1/opportunity_config.py
app/api/src/tests/api/api_v1/test_opportunity_config.py
app/api/src/tests/utils/opportunity_config.py

The endpoint previous returned the configs by the object id before and now returns all the configs related to study area.
Used in dashboard
:heavy_check_mark: :recycle: Refactored the test.
#1619

[FIX] Oportunity study area ocnfig endpoint bug :recycle: :lady_beetle: 

---

app/api/src/crud/crud_user.py
app/api/src/endpoints/v1/users.py

Study area id didn't add to user_study_area table for demo user endpoint.
When user wanted to get back to the demo study area at Goat UI could not find it any more.
Manually tested
#1543

[FIX] Add study area on user creation

---

app/client/src/components/isochrones/IsochroneThematicData.vue

Fixed the overflow of the isochrone result window when many POI's chosen.
@EPajares  Direct.

fix: data table of the isochrone window overflow

---

app/api/src/endpoints/v1/users.py

As the join clause of SQLAlchemy relation, could not get serialized by pydantic, it was done by converting data to dictionary and then edit.
Also as study_area is not serializable by itself, just ids were loaded.
We can also modify it using pydantic to remove the geom column and then serialize it in future.
Makes dashboard able to modify study areas for user
:warning: Just manual testing
#1618

[FIX] load study_areas and roles for user endpoint

---

app/api/src/crud/base.py
app/api/src/db/models/user.py
app/api/src/endpoints/v1/users.py

Ordering and Searching for endpoints at backend
sort items example at query attribute: `sorting=-id,email`
search is added to list users endpoint. Example: `q=webmaster`
:warning: Manually tested.
#1597

Ordering and search for endpoints

---

app/api/src/crud/base.py
app/api/src/db/models/geostore.py
app/api/src/db/models/layer_library.py
app/api/src/db/models/opportunity_config.py
app/api/src/db/models/static_layer.py
app/api/src/endpoints/v1/geostores.py
app/api/src/endpoints/v1/layer_library.py
app/api/src/endpoints/v1/opportunities.py
app/api/src/endpoints/v1/opportunity_config.py
app/api/src/endpoints/v1/static_layers_extra.py
app/api/src/endpoints/v1/users.py

Add sort and search for config endpoints.
Also changed the key `ordering` to `order_by`
The sorting keys should separated by comma and if we want to desc order, we may add a minus (dash) before key.
For example:
`order_by=email,-id`
It first orders by email and then, if emails were same, it will order by id in desc.
Added for the following endpoints:
- /config/layers/vector/static
- /config/layers/library/styles
- /config/layers/library
- /config/geostores
- /config/opportunities
- /config/opportunity-study-area
- /users
Test: :warning: manually tested
Related issue: #1597

Ordering and search for config endpoints

---

app/api/src/schemas/study_area.py

Fix for update/get layer_groups of study_area
Missed indicator for LayerGroupBase
Related issue: #1653

[FIX] study-area-settings endpoint

---

app/api/src/core/config.py
app/api/src/db/sql/init_remote_table.py

The first step to do combination with Raw data and production data is to create a connection between them.
These commits are created to upgrade/downgrade:
- Foreign server extension
- Foreign server itself
- Mapping user for foreign server
- Mapping schema to import foreign tables
- Importing foreign tables to mapping schema
Needed to prepare any database that's used for processing remote data.
:heavy_check_mark:  Manually tested for:
- upgrade_foreign_server
- downgrade_foreign_server
- upgrade_mapping_user
- downgrade_mapping_user
- upgrade_schema
- downgrade_schema
- upgrade_create_table
- downgrade_create_table
:x:  The following functions has not been tested yet:
- upgrade_extension
- downgrade_extension
**Related Issue** #1592

Chapar remote table

---

app/client/src/components/isochrones/Isochrones.vue

Fixed the issue by adding an if statement to the part of the code. It will basically check if it ain't a PT Isochrone.

[FIX] fixed the issue with the PT result isochrone

---

app/api/src/core/heatmap.py

Heatmap basic calculations

---

app/api/src/core/heatmap.py
app/api/src/crud/crud_heatmap.py

Fix for reading opp_matrix in different orientation (vertical/horizontal)
+ Fix for calculating empty data
Related issue: #1787

Heatmap calculations per grid

---

app/api/src/core/heatmap.py

[ADD] quantile_classify()  @-> heatmap.py

---

.gitignore
app/api/src/core/config.py
app/api/src/tests/api/api_v1/list_todos.sh
docker-compose.yaml

Separate env variables

---

.gitignore
app/api/.vscode/launch.json
app/api/src/core/heatmap.py
app/api/src/crud/crud_read_heatmap.py
app/api/src/schemas/heatmap.py

Related issue: #1925
Also:
- refactored heatmap_core to make it cleaner
- refactored crud_read_heatmap to remove minus classes but zeros
+ some other changes

Implement combined modified Gaussian function

---

app/api/src/core/heatmap.py
app/api/src/core/heatmap_cython.pyx
app/api/src/crud/crud_read_heatmap.py

Related issue: #1933 
Removed sorted grids from sorting function:
- Sorted grids converted data types from int to float that corrupted
- Also made sorting slower
- As we don't use sorted grids it's removed

Fix gravity parenting

---

app/client/src/components/core/UserDataUpload.vue
app/client/src/components/indicators/Indicators.vue
app/client/src/components/layers/filter/PoisAoisTree.vue
app/client/src/components/viewer/ol/Map.vue
app/client/src/store/modules/poisaois.js
app/client/src/style/OlStyleDefs.js

We structured the POIs in a better way. We avoided adding them to the layer, so we just saved them in the vuex state. The application is much faster now.
I also implemented a formula to calculate the right max zoom level where the POIs start to show up:
**log2(P / (W / 2000))**
**P:** The count of the POIs and AOIs
**W:** The width of the map in pixels
**Note!!! :** please check the data upload. I removed the dispatch because it was freezing my browser and because it would repeat the step of storing the POIs. Maybe we just make a process where we add them and not request them over again.

feat: A new way to deal with the POIs

---

app/api/.devcontainer.json
app/api/src/endpoints/deps.py
app/api/src/endpoints/v1/customizations.py
app/api/src/tests/api/api_v1/test_customizations.py
app/api/src/tests/api/api_v1/test_heatmap.py
app/api/src/tests/conftest.py

- 2 Examples Failed :heavy_multiplication_x: 
- 1 Time outed :hourglass: 
- 9 Passed :heavy_check_mark: 
Related issues:
- #1840 
- #1946

[TEST] for Heatmaps & Customizations 🧪

---

app/api/src/core/opportunity.py
app/api/src/crud/crud_isochrone.py
app/api/src/schemas/isochrone.py
app/api/src/utils.py
app/client/src/components/isochrones/Isochrones.vue
app/client/src/components/other/IsochroneAmenitiesLineChart.vue
app/client/src/locales/en.json
app/client/src/utils/IsochroneUtils.js

[ADD] Isochrone buffer

---

app/client/src/components/indicators/Indicators.vue
app/client/src/components/layers/layerTree/LayerTree.vue
app/client/src/components/viewer/ol/Map.vue
app/client/src/store/modules/isochrones.js

[fix]: Fixed some bugs in the client

---

app/client/src/store/modules/poisaois.js

There was a problem that basically the first POI from a category was not added to the POI object in the poi visualization layer. This leaded to the situation that one poi per category was missing in the visualization layer.
@Ebubeker

[FIX] Bug with pois when loading

---

app/client/src/components/isochrones/IsochroneThematicData.vue

Managed to fix the thematic data window when a multi isochron and a single isochrone are chosen. The issue was that when we activated single isochrone, switched to the graphs and tried to activate the multi isochrone, the resultViewType variable will still stay at the graphs eventho we changed selection and isochrone type. So I listened to isochrone selection changes and checked if it was a multi isochrone. if yes, I made it that it shows only the first resultViewType, which is the table.

fix: fixed the multiisochrone window

---

app/api/src/endpoints/v1/indicators.py

- Changed `crud_isochrone.calculate()` result from Response to byte
- Extracted study_area_bounds from `crud_isochrone.calculate()` out, as it was async. So it is fetched at endpoint.
- The result of `calculate()` is converted to hex string first and then saved to REDIS and converted back at results endpoint.
Related issue:
- #2073 
- #1841 
- #1828 
- #1739

Isochrone to celery

---

app/api/src/schemas/heatmap.py

+ Sort request examples by resolution
+ Add warning to the examples with higher resolution
Related issue:
- #2086

[DOC] sort request examples for heatmaps

---

app/api/src/utils.py

The file name now instead of the format `{isochrone/heatmap}.ext` is always zip and contain the format name as well.
For example: `heatmap-kml.zip` or `isochrone-geojson.zip`
Related issue:
- #2338

[ADD] meta info to converted file

---

app/client/package.json
app/client/src/components/isochrones/Isochrones.vue
app/client/src/components/viewer/print/PrintLegend.vue

I fixed the isochrone network, did the same thing as with the isochrone and multi Isochrone requests.

fix: fixed the isochrone network
