app/front_end/index.html, app/front_end/js/index_functions.js, app/front_end/js/interaction.js, app/front_end/js/isochrones.js, app/front_end/js/style.js
Fixed Heatmap layer ordering by adding a higher zIndex on Isochrones Layer. 
Added checkbox to toggle ways layer visibility. 
Added a different style for bridge and way.
Fixed the problem with ways visibility when isochrone is calculated.
=> Small Changes.

app/front_end/js/data_preparation.js
=> Fix accessibility index

_docs/quick_start.md
Made step 9 of the GOAT-setup documentation more clear (just minor wording and formatting changes).
=> Updated step 9 of the GOAT-setup

_docs/quick_start_vm.md
- Updated the docker commands
- Added one common error and how to solve it
=> Improvement of "quick_start_vm" documentation

app/client/public/static/app-conf.json, app/client/src/locales/al.json, app/client/src/locales/ar.json, app/client/src/locales/cn.json, app/client/src/locales/de.json, app/client/src/locales/en.json, app/client/src/locales/es.json, app/client/src/locales/fr.json, app/database/data_preparation/SQL/create_tables.sql, app/database/data_preparation/SQL/network_preparation.sql, app/geoserver/geoserver_data/gwc-layers/LayerInfoImpl-7407ec68_16e4f6e0398_6bff.xml, app/geoserver/geoserver_data/gwc-layers/LayerInfoImpl-7440d3b_16da56943d6_-7ffd.xml, app/geoserver/geoserver_data/workspaces/cite/database/ways/layer.xml, app/geoserver/geoserver_data/workspaces/cite/database/ways_lit/featuretype.xml, app/geoserver/geoserver_data/workspaces/cite/database/ways_wheelchair/featuretype.xml, app/geoserver/geoserver_data/workspaces/cite/database/ways_wheelchair/layer.xml, app/geoserver/geoserver_data/workspaces/cite/styles/lit.sld, app/geoserver/geoserver_data/workspaces/cite/styles/lit.xml, app/geoserver/geoserver_data/workspaces/cite/styles/style_wheelchair.sld, app/geoserver/geoserver_data/workspaces/cite/styles/style_wheelchair.xml
- Integration of further attributes to table ways
- Integration of further columns to variable container
- Creation of the layers "Illuminance" and "Wheelchair Usability" in Geoserver
=> Added Layers "Illuminance" and "Wheelchair Usability"

_docs/contribute_docs.md
=> Improved contribute_docs

_docs/contribute_docs.md
- improved the wording
- deleted an unneeded step
=> Improved the "contribute_docs"

app/config/goat_config.yaml, app/database/data_preparation/SQL/types.sql, app/database/database_functions/other/pois_visualization.sql, app/database/database_functions/routing/isochrones_api.sql, app/database/database_functions/routing/pgrouting_edges.sql, app/geoserver/geoserver_data/workspaces/cite/database/footpath_width/featuretype.xml, app/geoserver/geoserver_data/workspaces/cite/database/pois_info/featuretype.xml
Opening Hours:
- outsourced query of Geoserver layer "pois_test" in function "pois_visualization" 
--> checks, if opening hours are submitted by the user or not (default values = 9999) and executes corresponding query
- created function type for the new function "pois_visualization"
- adjusted "isochrones_api" to the adjusted default values
Individual Routing:
- stored elderly and wheelchair speed in the variable_container
=> included opening hours in the POIs layer

app/client/src/store/modules/isochrones.js, app/database/database_functions/other/fetch_and_extrapolate.sql, app/database/database_functions/other/pois_visualization.sql, app/database/database_functions/routing/isochrones_alphashape.sql, app/database/database_functions/routing/isochrones_api.sql, app/database/database_functions/routing/multi_isochrones.sql, app/database/database_functions/routing/pgrouting_edges.sql, app/database/database_functions/routing/pgrouting_edges_multi.sql, app/database/database_functions/routing/pois_multi_isochrones.sql
changed routing_profiles:
'wheelchair' --> 'walking_wheelchair'
'standard' --> 'walking_standard'
'elderly' --> 'walking_elderly' 
'safe_night' --> 'walking_safe_night'
=> updated names of routing_profiles regarding the upcoming implementation of cycling

.gitignore, .travis.yml, Makefile, app/api/app.js, app/client/.env, k8s/api.tpl.yaml, k8s/client.tpl.yaml
@EPajares I'm missing env vars needed for the client. Could you please send it to me?
We can merge this when it's approved. I've commented out the auto deployment of `client` till I get the env vars list from you 👍
=> Deploy API and Client to K8s using TravisCI

Makefile, k8s/api.tpl.yaml, k8s/client.tpl.yaml, k8s/general.yaml, k8s/letscrypt.yaml
Next step is to utilize these configs to expose K8s service to public internet over SSL.
=> Setup Nginx, LoadBalancer and Letscrypt

app/client/public/static/app-conf.json, app/client/src/components/layers/edit/Edit.vue, app/client/src/components/ol/Map.vue, app/client/src/controllers/OlBaseController.js, app/client/src/controllers/OlEditController.js, app/client/src/style/OlStyleDefs.js, app/client/src/utils/Layer.js
Now the GetInfo should work for all layers that have the 'queryable: true' attribute.
=> WIP - Get Info for all layers.

.gitignore, .travis.yml, app/geoserver/Dockerfile, app/mapproxy/Dockerfile, app/print/Dockerfile, k8s/api.tpl.yaml, k8s/client.tpl.yaml, k8s/geoserver.tpl.yaml, k8s/mapproxy.tpl.yaml, k8s/print.tpl.yaml
=> Deploy geoserver, print and mapproxy

app/client/public/static/app-conf.json, app/client/src/components/core/Settings.vue, app/client/src/components/core/SideDrawer.vue, app/client/src/components/layers/filter/Pois.vue, app/client/src/components/layers/layerTree/LayerTree.vue, app/client/src/components/ol/Map.vue, app/client/src/factory/layer.js
- Fixed #307 (The symbol is now a flag. We can change it later if we are going to add more settings)
- Fixed #308 (I added an attribute in app-conf.json "requiresPois" to determine if the layer needs pois layer active or not)
- "Add Time Filter" Now we can change the value in app-conf.json . (componentConf.pois.filters.timeBasedCalculations) can have 2 values ("yes"/"no").
=> - Fixed #308 , #307 and added "Add time filter" option to app-conf.json

app/client/public/static/app-conf_master.json, app/database/database_functions/other/closest_vertex.sql
Made a new version of the "app-conf" file which excludes the routing profiles "elderly" and "safe-night".
=> Adjusted the config in order to implement this branch into master

k8s/geoserver.tpl.yaml
=> Database setup

_docs/quick_start_vm.md
Exchanged the command for the new setup.
=> Updated the quick_start_vm doc

app/client/src/components/core/Settings.vue, app/client/src/components/layers/edit/Edit.vue, app/client/src/controllers/OlEditController.js, app/client/src/controllers/OlEditLayerHelper.js, app/client/src/locales/en.json, app/client/src/locales/sq.json, app/client/src/style/OlStyleDefs.js
- Added different Validation for upload module ( like missing required fields, geometry type etc.)
- Improved edit interactions to work with the uploaded data.
=> (WIP) Draw Scenario

.travis.yml, k8s/api.tpl.yaml, k8s/geoserver.tpl.yaml, k8s/mapproxy.tpl.yaml, k8s/postgres.tpl.yaml, k8s/print.tpl.yaml
Deployment to multi envs:
https://demo.open-accessibility.org/ (development)
https://beta.open-accessibility.org/ (beta)
=> Add multiple deployments

docker-compose.yaml
=> invoke-travis build

Vagrantfile, app/client/public/static/app-conf_Hasenbergl.json, app/client/src/locales/de.json, app/client/src/locales/en.json, app/database/data_preparation/SQL/layer_preparation.sql, app/database/data_preparation/SQL/network_preparation.sql, app/geoserver/geoserver_data/workspaces/cite/database/street_crossings/featuretype.xml
- improved street crossings 
- improved classification illuminance
- removed folder "scripts" from vagrantfile
- improved translation
- created an app-conf file for the Hasenbergl version
=> Walkability improvements + translations

index.html, versions.html
- Improved visability of survey by adding a banner to the front-page
- Added an introcution text to the "versions" page
=> Website improvements

app/client/public/static/app-conf.json, app/client/src/components/core/Settings.vue, app/client/src/components/layers/edit/Edit.vue, app/client/src/factory/layer.js, app/client/src/locales/de.json, app/client/src/locales/en.json
+ improved the translations
+ added a hint about the needed data type for uploading scenario files
+ limited the available languages to German and English
=> Translations

app/client/public/static/app-conf.json
added note for expected data type to **way scenario**
=> Added a missing line in app-conf 

app/client/src/locales/de.json
added German translation for new words & checked existing translations
=> improved German translation

app/print/templates/goat/A3_Landscape.jrxml, app/print/templates/goat/A3_Portrait.jrxml, app/print/templates/goat/A4_Landscape.jrxml, app/print/templates/goat/A4_Portrait.jrxml
I increased the textbox size to fully use all the space we have. But it seems like the settings also have to be adjusted somewhere, as the text seems to be limited to a certain number of characters. 
#518
=> Increased "title" textboxes of printing templates

app/config/goat_config.yaml
Improved documentation for input variables in goat_config for data_fusion
=> Data fusion input  documentation in goat_config

_posts/2020-04-25-mapillary.md
Corrected Santiagos name and added Emna as author
=> corrected authors name

app/geoserver/geoserver_data/workspaces/cite/database/landuse_osm/featuretype.xml, app/geoserver/geoserver_data/workspaces/cite/styles/style_osm_landuse.sld
=> improved the osm_landuse layer

_posts/2020-05-21-Blogpost-Testcycles.md
=> blogpost testcycles

app/geoserver/geoserver_data/gwc-layers/LayerInfoImpl--235fe2ae_1722d40b410_-7c5b.xml, app/geoserver/geoserver_data/gwc-layers/LayerInfoImpl--235fe2ae_1722d57dc53_3174.xml, app/geoserver/geoserver_data/gwc-layers/LayerInfoImpl--235fe2ae_1722d62e2d4_15d8.xml, app/geoserver/geoserver_data/gwc-layers/LayerInfoImpl--235fe2ae_1722d62e2d4_15da.xml, app/geoserver/geoserver_data/workspaces/cite/database/mapping_pois_opening_hours/featuretype.xml, app/geoserver/geoserver_data/workspaces/cite/database/mapping_pois_opening_hours/layer.xml, app/geoserver/geoserver_data/workspaces/cite/database/mapping_way_surface/featuretype.xml, app/geoserver/geoserver_data/workspaces/cite/database/mapping_way_surface/layer.xml, app/geoserver/geoserver_data/workspaces/cite/database/mapping_ways_speed/featuretype.xml, app/geoserver/geoserver_data/workspaces/cite/database/mapping_ways_speed/layer.xml, app/geoserver/geoserver_data/workspaces/cite/database/mapping_ways_wheelchair/featuretype.xml, app/geoserver/geoserver_data/workspaces/cite/database/mapping_ways_wheelchair/layer.xml
Created 4 new GeoServer layers for the osm mapping challenges:
- mapping_ways_wheelchair
- mapping_ways_speed (already complete in FFB, but could be useful for other cities)
- mapping_way_surface
- mapping_pois_opening_hours
=> Geoserver layers for osm challenges

app/geoserver/geoserver_data/workspaces/cite/database/mapping_pois_opening_hours/featuretype.xml, app/geoserver/geoserver_data/workspaces/cite/database/mapping_way_surface/featuretype.xml, app/geoserver/geoserver_data/workspaces/cite/database/mapping_ways_wheelchair/featuretype.xml
changed the basis tables from "ways" / "pois_userinput" to "ways_mapping" / "pois_mapping"
=> improved mapping-layers

app/client/src/locales/de.json, app/client/src/locales/en.json
=> improved the osm mapping descriptions

app/client/public/static/app-conf.json, app/client/src/locales/de.json, app/client/src/locales/en.json
=> added more intensive descriptions to the mapping challenges

app/client/public/static/app-conf.json, app/client/public/static/app-conf_ffb.json, app/client/src/locales/de.json, app/client/src/locales/en.json
I added some wms layers that could be interesting for Freising:
- flooding areas
- dykes
- drinking water protection areas
=> New wms layers

app/geoserver/geoserver_data/workspaces/cite/styles/style_heatmap.sld, app/geoserver/geoserver_data/workspaces/cite/styles/style_heatmap_area_isochrone.sld
=> German translations heatmaps

app/geoserver/geoserver_data/workspaces/cite/styles/style_mapping_ways.sld
increased the width of the Mapping Ways
=> improved style ways mapping

app/geoserver/geoserver_data/global.xml, app/geoserver/geoserver_data/workspaces/cite/styles/style_heatmap_luptai.sld, app/geoserver/geoserver_data/workspaces/cite/styles/style_heatmap_population.sld, app/geoserver/geoserver_data/workspaces/cite/styles/style_heatmap_population.xml
=> german translation heatmap legends

app/geoserver/geoserver_data/security/layers.properties, app/geoserver/geoserver_data/workspaces/cite/styles/style_highway_categories.sld, app/geoserver/geoserver_data/workspaces/cite/styles/style_highway_categories_aggregated.sld, app/geoserver/geoserver_data/workspaces/cite/styles/style_highway_categories_aggregated.xml
added "motorways" and "motorway_links" to the visualization
=> improved "street category" styles

app/client/src/locales/de.json, app/client/src/locales/en.json
improved the wording according to the feedback from the planning workshop in FFB
=> Translation

app/database/data_preparation/SQL/layer_preparation.sql
I added all necessary attributes to the table "footpath_union"
=> adjusted layer_preparation

app/config/goat_config.yaml
I added the different values to calculate the walkability index
=> updated variable container

app/database/database_functions/walkability/select_weight_walkability.sql, app/database/database_functions/walkability/select_weight_walkability_range.sql, app/database/database_functions/walkability/walkability.sql
- added the function "select_weight_walkability"
- started to calculate the scores in "walkability.sql"
=> walkability weights

app/database/database_functions/walkability/walkability.sql
Update vegetation indicator, now including green land uses, the weighting is:
trees = 0.3
green land  uses 0.7
=> Update vegetation indicator

app/database/database_functions/walkability/walkability.sql
=> New green land uses added

app/client/src/components/viewer/ol/controls/Legend.vue, app/client/src/utils/LegendRenderer.js
=> Legend Improvement

app/database/data_preparation/SQL/layer_preparation.sql
=> lit classification

app/client/src/components/layers/layerTree/LayerTree.vue, app/client/src/components/viewer/ol/Map.vue
Implemented attribute level legend
=> Implemented Attribute Level Legend

app/client/public/static/app-conf.json, app/client/public/static/layer-styles/styles/ways_walkability.json, app/database/data_preparation/SQL/layer_preparation.sql, app/database/data_preparation/SQL/network_preparation1.sql, app/database/data_preparation/SQL/walkability.sql, app/database/data_preparation/walkability.csv, app/database/database_functions/data_preparation/group_index.sql, app/database/database_functions/data_preparation/select_full_weight_walkability.sql, app/database/database_functions/layers_api/street_furniture.sql, app/database/database_functions/layers_api/street_furniture_bicycles.sql, app/database/database_functions/layers_api/ways_lit.sql, app/database/database_functions/layers_api/ways_walkability.sql
I now pushed this here, but as discussed we should probably outsource parts of the queries to the data preparation
=> included Mapillary data

app/client/src/components/layers/changeStyle/FillVectorStyle.vue, app/client/src/components/layers/changeStyle/IconVectorStyle.vue, app/client/src/components/layers/changeStyle/LineVectorStyle.vue, app/client/src/components/layers/layerTree/LayerTree.vue, app/client/src/components/viewer/ol/Map.vue, app/client/src/components/viewer/ol/controls/Legend.vue
Implemented Change Style Feature
=> Change style layers

app/client/src/components/layers/edit/Edit.vue
Implementing Feature Undo Redo functionality
=> Implementing Feature Undo Redo functionality

app/client/src/components/layers/changeStyle/FillVectorStyle.vue, app/client/src/components/layers/changeStyle/IconVectorStyle.vue, app/client/src/components/layers/changeStyle/LineVectorStyle.vue
Implementing function to revert back to original style color
=> Implementing function to revert back to original style color

app/client/src/components/layers/edit/Edit.vue, app/client/src/controllers/OlEditController.js
Updating Undo Redo Functionality
=> Updating Undo Redo Functionality

app/client/src/components/layers/edit/Edit.vue, app/client/src/controllers/OlEditController.js
=> Undo Redo Small Fixes

app/client/src/components/isochrones/Isochrones.vue, app/client/src/components/layers/changeStyle/FillVectorStyle.vue, app/client/src/components/layers/changeStyle/IconVectorStyle.vue, app/client/src/components/layers/changeStyle/LineVectorStyle.vue, app/client/src/components/layers/changeStyle/StyleDialog.vue, app/client/src/components/layers/edit/Edit.vue, app/client/src/components/layers/layerOrder/LayerOrder.vue, app/client/src/components/layers/layerTree/LayerTree.vue, app/client/src/components/viewer/ol/controls/InLegend.vue, app/client/src/components/viewer/ol/controls/Legend.vue, app/client/src/main.js
Implemented Reset style for 
1. individual attribute style reset
2. whole layer reset style
Removed the language bug for inLegend in layer tree
Removed isochrone and study area visibiliy stack issue
Implemented minor changes for undo_redo
=> Implementing Reset Style, removing change language bug and other issues

.gitignore, app/api/poetry.lock, app/api/pyproject.toml, app/api/src/exts/cpp/tests/isochrone_surface.py, app/api/src/exts/cpp/tests/test_isochrone_surface.cpp
Now we can see the output of interpolation via the command:
`python /app/src/exts/cpp/tests/isochrone_surface.py` Which will be saved to `/app/NearestNDInterpolate.png` inside the container.
=> Isochrone Interpolation

.gitignore, app/api/src/exts/cpp/tests/isochrone_surface.py
To check the output after running the following command at `/app` directory, we can get the result at `/app/costs.bin`.
run the command:
`python /app/src/exts/cpp/tests/isochrone_surface.py`
Also we can use the [GHex](https://wiki.gnome.org/Apps/Ghex) to read the binary.
=> [ADD] test for writing costs as binary :alembic:

app/api/src/endpoints/v1/api.py, app/api/src/endpoints/v1/layer_library.py, app/api/src/schemas/__init__.py, app/api/src/schemas/layer_library.py, app/api/src/tests/api/api_v1/test_layer_library.py, app/api/src/tests/utils/layer_library.py
:white_check_mark: CRUD tests for style library endpoints
Related issue: #1340
=> Style library endpoint TESTS

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/concrete-task-.md, .github/ISSUE_TEMPLATE/feature_request.md
=> Add issue templates

app/api/src/core/dijkstra.py, app/api/src/core/isochrone.py, app/api/src/tests/utils/isochrone.py
Rewrite Isochrone calculation in python
Related to #1353
As a replace for PR #1377 
We would have more control over it as it is in python (main scripting language of GOAT)
:warning: Not tested yet
=> Multi isochrone performance python

app/api/src/core/dijkstra.py, app/api/src/core/isochrone.py, app/api/src/crud/crud_isochrone.py
Add get_single_depth_grid() to crud_isochrone
=> [TEST] Multi isochrone performance python

app/api/src/core/dijkstra.py, app/api/src/core/isochrone.py
Replace Sparse matrix with simple adjacency dictionary.
=> Fix dijkstra

app/api/src/crud/__init__.py, app/api/src/crud/crud_geostore.py, app/api/src/crud/crud_study_area.py, app/api/src/crud/crud_study_area_geostore.py, app/api/src/db/models/geostore.py, app/api/src/endpoints/v1/api.py, app/api/src/endpoints/v1/geostores.py, app/api/src/resources/enums.py, app/api/src/schemas/__init__.py, app/api/src/schemas/geostore.py, app/api/src/tests/api/api_v1/test_geostores.py, app/api/src/tests/utils/geostores.py
Add Endpoints to CRUD Geostores and also add/remove/list them from Study Areas
Just tested manually
closes #1391
=> Geostore endpoint

app/client/src/components/core/About.vue, app/client/src/components/core/LeftPanel.vue, app/client/src/components/layers/importLayers/ImportExternalLayers.vue, app/client/src/components/layers/importLayers/PreDefinedGeoportals.vue, app/client/src/components/layers/layerTree/LayerTree.vue, app/client/src/locales/en.json, app/client/src/plugins/vuetify.js, app/client/src/views/Auth.vue
Created an Error Handler for handling layers that are out of the map boundaries
It compares 16 cases inside 4 if statements. It was a bit tough since OpenLayers had only 2 methods to compare layers which were kind of useless in our case since we have layers with different mases
=> Error Handling for layers that are out of the map boundaries

app/client/src/components/layers/changeStyle/IconVectorStyle.vue, app/client/src/components/layers/changeStyle/StyleDialog.vue, app/client/src/components/layers/layerTree/LayerTree.vue, app/client/src/components/print/Print.vue, app/client/src/components/viewer/print/PrintViewer.vue, app/client/src/plugins/vuetify.js
I managed to fix the issue that Ulrike opened for the translation when printing.
I also fixed the text above the scale line so it doesn't show up anymore when you try to print the map.
The third issue that I managed to finish is about the vector styling. Now you are able to modify the vector points. You have the availability to import image from desktop or import image via URL. You can also change the icon size.
=> 3 more issues have been finished and are ready for review

app/api/src/schemas/geostore.py, app/api/src/tests/api/api_v1/test_geostores.py, app/api/src/tests/utils/geostores.py
- Create random request_example each time we access it:
- Refactor request example and replace it by class
Example name: test_skouijfnfyyjbrancylsaqyhumxalkbu
As the name column fixed to have unique constraint we would have unique name for unit testing.
Ran the list test unit again.
#1391
=> [TEST] fix sample_geostore_creator()

app/client/src/components/viewer/ol/Map.vue, app/client/src/plugins/vuetify.js
It works only for some layers for now. I had to create a new overlay since the logic of the other overlay was very different. The thing is that it works and it can also be used for other wms/wmts layers that support it. It could have been way more better but this is all I could do. Maybe we can work in it in the future to improve it and make it available for every single queryable wms layer.
=> Added a getInfo to the wms inner layers.

app/client/public/static/404.html
=> feat: 404 page

app/api/src/crud/crud_isochrone.py
Extract reached opportunities to the exported file
Related issue: #1348
=> [REFACTOR] export isochrone

app/client/public/static/404.html
=> fix: replaced image with text

app/api/Dockerfile
Poetry installation file from GitHub was deprecated
Thanks @cinaaaa for finding this.
=> [FIX] poetry install :package: 

app/api/.devcontainer.json, app/api/scripts/patch/utils.diff, app/api/scripts/patch_fastapi_utils.sh, app/api/scripts/post-create.sh
=> [REFACTOR] devcontainer performance

app/client/src/components/heatmaps/Heatmaps.vue, app/client/src/components/heatmaps/modifyLayer/ModifyDialog.vue, app/client/src/locales/en.json
The components are ready to be put on work. For the moment everything is static.
=> PT indicators 

app/client/package-lock.json, app/client/src/components/indicators/Indicators.vue, app/client/src/locales/en.json, app/client/src/style/OlStyleDefs.js
When zooming now pie charts are available. It will be better if we also store the colors in the Vuex store if it is possible.
=> Styling is done, the colors are randomly chosen 

app/client/src/components/indicators/Indicators.vue, app/client/src/components/indicators/TimePicker.vue, app/client/src/components/isochrones/Isochrones.vue, app/client/src/components/other/IsochroneAmenitiesRadarChart.vue, app/client/src/locales/en.json, app/client/src/utils/Helpers.js
I managed to fix: 
- Station count and ÖV Güteklasse do not always reflect time picker #1519 (still needs to be checked since it has some weird crashes)
- "No title fetched"? #1516 **(DONE)**
- Missing translation in spider web #1513 **(DONE)**
- Minute count not working? #1511 **(DONE)**
- Remove hardcoded parts and use translation for transit isochrones #1510 **(DONE)**
At Remove hardcoded parts and use translation for transit isochrones #1510 I only added the translation in english, so it is ready to be translated in the other languages.
=> Most of the issues have been fixed

app/api/src/endpoints/v1/isochrones.py, app/api/src/main.py, app/api/src/run_time_method_calls.py
Used for compile numba for the first time.
Related issue: #1521
=> [Feat] Add startup call for isochrone calculation

app/client/src/components/indicators/Indicators.vue, app/client/src/components/indicators/TimePicker.vue, app/client/src/components/isochrones/Isochrones.vue, app/client/src/components/other/IsochroneAmenitiesRadarChart.vue, app/client/src/locales/en.json, app/client/src/utils/Helpers.js
Reverts goat-community/goat#1522
=> Revert "Most of the issues have been fixed"

app/client/src/components/viewer/print/PrintLegend.vue
=> fix: remove study areas on the print legend side

app/api/src/crud/crud_indicator.py, app/api/src/endpoints/v1/indicators.py, app/api/src/schemas/indicators.py
- add station_config to required arguments and remove the default config
:x: :alembic: Manual test failed
=> [REFACTOR] compute_oev_gueteklassen endpoint

app/client/src/components/isochrones/IsochroneColorPicker.vue, app/client/src/components/isochrones/IsochroneThematicData.vue, app/client/src/components/isochrones/Isochrones.vue, app/client/src/components/other/IsochroneAmenitiesLineChart.vue, app/client/src/components/other/IsochroneAmenitiesRadarChart.vue, app/client/src/components/viewer/viewer.vue, app/client/src/store/modules/isochrones.js, app/client/src/style/OlStyleDefs.js
For now the colors aren't the best since Dilan is still finding them but it does the job to help me build the logic at least. Everything looks way more interactive and better.
There are still some small issues to be solved until this pull request can be merged.
=> Added colors to the Isochrone & Now you can change the color too

app/api/src/crud/crud_indicator.py, app/api/src/crud/crud_isochrone.py, app/api/src/db/sql/functions/indicators/count_public_transport_services_station.sql
=> [FIX] for güteklassen and PT-isochrones

app/client/src/components/isochrones/IsochroneColorPicker.vue, app/client/src/components/other/DocumentationDialog.vue, app/client/src/components/viewer/viewer.vue, app/client/src/store/modules/isochrones.js
Managed to finish both of the tasks
=> isochrone color changes and documentation height fixed

app/client/src/components/isochrones/IsochroneThematicData.vue
Added The "Traveltime (minutes)" next to slider
=> Indicated that the isochrone has Travel time based on minutes

app/client/src/components/isochrones/IsochroneThematicData.vue, app/client/src/locales/de.json, app/client/src/locales/en.json
=> [FIX] the traveltime (minutes) translation

app/api/src/db/models/grid.py, app/api/src/db/models/traveltime_matrix.py
Fixed.
But the unique property needs update for sqlmodel
Related issue: #1636
=> Fix traveltimematrix relation

app/api/src/crud/crud_isochrone.py
=> [FIX] reverted dates changes

app/api/src/endpoints/v1/users.py
Add study_area and roles to returned JSON when creating a new user.
Related issue: #1643 #1618
=> [ADD] study_areas and roles when create new user

app/api/src/endpoints/v1/users.py
Remote hashed_password from json
Related PR: #1659 #1618
=> [FIX] security issue remote hashed_password

app/api/src/crud/crud_heatmap.py, app/client/src/components/isochrones/IsochroneColorPicker.vue, app/client/src/components/isochrones/Isochrones.vue, app/client/src/components/viewer/viewer.vue, app/client/src/style/OlStyleDefs.js, app/client/src/utils/Helpers.js
There were some issues at the isochrone color picker. The isochrone colors couldn't be reset after closing the dialogue and reopening it. Also another issue is that if you left the dialog open and clicked another isochrone, the dialogue wouldn't update therefore you did not know which isochrone you were editing. So basically I added an if statement which checks if there is any dialog open. If yes then the selection will not be made.
To have a better understanding you could also check the code
=> [FIX] Fixed some issues at the isochrone color picker

app/client/src/components/isochrones/IsochroneColorPicker.vue
Now it is working properly.
#1673
=> Added the color picker canva

app/client/src/components/isochrones/IsochroneColorPicker.vue
=> [FIX] removed the swatches

app/api/src/endpoints/v1/api.py, app/api/src/endpoints/v1/system.py, app/api/src/main.py, app/api/src/resources/enums.py, app/api/src/schemas/system.py
=> Add put method for system status

app/client/src/components/isochrones/IsochroneThematicData.vue, app/client/src/components/isochrones/Isochrones.vue, app/client/src/utils/Helpers.js
Now it works better.
I have also structured the code a bit better by adding some functions, that are used more than once, to the helpers file in the utils.
=> [FIX] Fixed the isochrone bug

app/api/src/db/models/__init__.py, app/api/src/db/models/customization.py, app/api/src/endpoints/v1/customizations.py, app/api/src/schemas/__init__.py, app/api/src/schemas/customization.py
=> [ADD] customization base CRUD endpoints

app/client/src/components/isochrones/Isochrones.vue
=> [FIX] pois count scenario_id

app/api/src/crud/crud_isochrone.py, app/api/src/db/sql/functions/indicators/reachable_population_polygon.sql, app/client/src/components/isochrones/Isochrones.vue
=> Fix multiisochrone population count

app/client/src/plugins/i18n.js
I managed to integrate it easily by changing a couple of stuff. Now we are able to manage the translations from POEditor. I tried it and it worked well for me by using github pages.
I will also check for automatic pushes to github repo when we change smth since for now we have to push it manually from POEditor.
=> Translation is integrated in the GOAT application

app/client/src/components/isochrones/IsochroneColorPicker.vue, app/client/src/components/isochrones/IsochroneThematicData.vue, app/client/src/components/isochrones/Isochrones.vue, app/client/src/components/other/IsochroneAmenitiesLineChart.vue, app/client/src/components/styling/StyleDialog.vue, app/client/src/components/viewer/viewer.vue
Solved the reset style button in the isochrone calculation. #1709
Solved the graphs too.
=> solved some of the feedback

app/client/src/components/isochrones/IsochroneThematicData.vue, app/client/src/components/isochrones/Isochrones.vue, app/client/src/style/OlStyleDefs.js
=> [FIX]: fixed the poi issue and the multi isochrone

app/client/src/style/OlStyleDefs.js
=> changed the comparison

app/client/src/components/viewer/ol/Map.vue, app/client/src/style/OlStyleDefs.js
Since It was a small change I will also push this one here
=> [Fix]: fixed the page order in the POI & Indicator overlay

app/client/src/components/isochrones/IsochroneColorPicker.vue, app/client/src/components/isochrones/IsochroneThematicData.vue, app/client/src/style/OlStyleDefs.js
I just had to adjust the calculation number there too. Now everything works fine
=> [FIX]: fixed the table problem

app/api/src/crud/crud_user.py, app/api/src/endpoints/v1/users.py, app/api/src/schemas/user.py
=> Fix update user

app/api/src/core/isochrone.py, app/api/src/crud/crud_heatmap.py
Computing the starting ids works pretty well, the only problem appears when we have to access the computed data.
=> Implementing Multiprocessing in the Heatmaps

app/api/src/crud/crud_heatmap.py
=> added the options to save the pois in the folder

app/api/src/core/isochrone.py, app/api/src/crud/crud_isochrone.py
=> [REFACTOR] isochrone performance

app/api/src/endpoints/v1/users.py
=> Merging fixes

app/api/src/crud/crud_heatmap.py, app/api/src/schemas/heatmap.py
=> Heatmap Classification/Separation/Schema

app/api/src/crud/crud_heatmap.py
=> [FIX] wrong calculation of mins

app/api/src/core/config.py, app/api/src/crud/crud_heatmap.py
- REFACTOR to use path.join
- Move cache paths to settings
- Move multiprocessing_bulk_size to settings
Related issue: #1799
=> Refactor crud_heatmap

.gitignore, app/api/src/tests/api/api_v1/list_todos.sh
Run the following command in /tests directory to list undone TODOs:
`bash list_todos.sh`
Related issue: #1828
=> [ADD] bash to list unwritten and mentioned tests

app/api/src/core/heatmap.py, app/api/src/crud/crud_read_heatmap.py
=> Map Crud heatmap do calculations

.gitignore, app/api/src/cache/opportunity_matrices/cycling/.gitignore, app/api/src/cache/opportunity_matrices/public_transport/.gitignore, app/api/src/cache/opportunity_matrices/walking/.gitignore, app/api/src/cache/opportunity_matrices/walking/standard/.gitignore, app/api/src/cache/traveltime_matrices/cycling/.gitignore, app/api/src/cache/traveltime_matrices/public_transport/.gitignore, app/api/src/cache/traveltime_matrices/walking/.gitignore, app/api/src/cache/traveltime_matrices/walking/standard/.gitignore, app/api/src/tests/api/api_v1/list_todos.sh
=> Fix gitignore for cache

app/api/src/crud/crud_compute_heatmap.py
=> Crud heatmap do calculations

app/api/src/core/heatmap.py, app/api/src/crud/crud_compute_heatmap.py, app/api/src/crud/crud_read_heatmap.py, app/api/src/schemas/heatmap.py
=> Combine heatmap calculations as dataframe like

app/api/src/core/heatmap.py, app/api/src/crud/crud_read_heatmap.py, app/api/src/endpoints/v1/indicators.py, app/api/src/schemas/heatmap.py, app/api/src/utils.py
=> [ADD] GeoJSON Generator for crud_read_heatmap

.gitignore, app/api/src/core/config.py, app/api/src/core/heatmap_cython.pyx, app/api/src/crud/crud_compute_heatmap.py, app/api/src/crud/crud_read_heatmap.py, app/api/src/schemas/heatmap.py
=> Connectivity heatmap

app/api/src/core/heatmap.py, app/api/src/core/r5.py, app/api/src/jsoline.py, app/api/src/utils.py
=> Fix walking matrix branch

.gitignore, app/api/src/crud/crud_scenario.py, app/api/src/endpoints/v1/scenarios.py, app/api/src/schemas/scenario.py
=> Broken scenario

app/api/src/core/config.py, app/api/src/core/heatmap.py, app/api/src/crud/crud_read_heatmap.py, app/api/src/tests/core/test_heatmap.py
=> Weighted heatmap calculations

app/client/src/factory/layer.js
=> fix: added the new connectivity heatmap endpoint to the client 

app/client/src/store/modules/isochrones.js, app/client/src/store/modules/map.js, app/client/src/store/modules/poisaois.js, app/client/src/utils/LegendRenderer.js
These issues have been fixed in this PR:
Further additions in this PR:
=> fix: fixed 2 last issues

app/api/src/workers/method_connector.py, app/client/src/style/OlStyleDefs.js
=> reduced icon size poi

README.md
=> Fixed bugs

app/api/.devcontainer.json, app/api/src/endpoints/v1/study_area.py, app/api/src/schemas/study_area.py
=> [HOTFIX] Fix study area settings

app/client/src/components/layers/edit/Edit.vue, app/client/src/components/viewer/ol/controls/InLegend.vue, app/client/src/store/modules/isochrones.js, app/client/src/style/OlStyleDefs.js
This pull request includes also the changes made to the pt indicator legend. It only shows the main ones.
=> Hotfix: Fixed the scenario Z-Index

docs/docs/backend/_category_.json, docs/docs/backend/architecture.md, docs/docs/data-preparation/_category_.json, docs/docs/data-preparation/cli.md, docs/docs/frontend/_category_.json, docs/docs/frontend/cli.md, docs/docs/intro.md, docs/docs/tutorial-basics/_category_.json, docs/docs/tutorial-extras/_category_.json, docs/static/diagrams/out/container_v2.svg, docs/static/diagrams/src/container_v2.puml
=> [WIP] Base documentation

app/client/src/components/layers/layerOrder/LayerOrder.vue, app/client/src/components/layers/layerTree/LayerTree.vue, app/client/src/main.js
@EPajares can you make sure to try it in your devices since in mine it works well. But I am a bit skeptical about this.
=> fix: fixed the translation problem

app/client-v2/apps/goat/pages/404.tsx, app/client-v2/packages/ui/components/Button.tsx, app/client-v2/packages/ui/components/Card/Card.tsx, app/client-v2/packages/ui/components/Divider.tsx, app/client-v2/packages/ui/components/Lists/ChipList.tsx, app/client-v2/packages/ui/components/SlideShow.tsx, app/client-v2/packages/ui/components/temporary/CardList.tsx, app/client-v2/packages/ui/components/temporary/Home.tsx, app/client-v2/packages/ui/components/temporary/NewsLetterSection.tsx, app/client-v2/packages/ui/components/temporary/index.ts, app/client-v2/packages/ui/components/theme.ts, app/client-v2/packages/ui/package.json, app/client-v2/packages/ui/stories/components/Alert.stories.tsx, app/client-v2/packages/ui/stories/components/Card Components/Card.stories.tsx, app/client-v2/packages/ui/stories/components/Divider.stories.tsx, app/client-v2/packages/ui/stories/components/Home.stories.tsx, app/client-v2/packages/ui/stories/components/SlideShow.stories.tsx
I have added everything that is in the Figma design. I had to change some things in the button, for the ternary variant of the button. Basically I made it be dark blue on light mode and light in dark mode. 
Besides this I have created another atomic component, the slideshow, it works fine. And I have also added the email subscription section. I would say overall it is finished, although it still might need changes because it isn't perfect, still I have to play a bit more with the typography in the future.
=> feat: added the Home page (currently is only responsive till 1000px)

app/api/src/crud/crud_isochrone.py, app/api/src/utils.py
=> Isochrone convert

app/api/src/core/heatmap/heatmap_core.py, app/client/src/store/modules/poisaois.js
=> Hotfix heatmap population

app/api/src/utils.py
- Formerly, it was generating FlatGeoBuf instead of GeoBuf
=> [FIX] geobuf output format

app/api/src/core/heatmap/heatmap_compute.py, app/client/src/store/modules/poisaois.js
=> Merging Fix

app/client/src/store/modules/poisaois.js
=> fix: aoi count

app/api/src/core/heatmap/heatmap_read.py, app/api/src/schemas/heatmap.py, app/api/src/workers/method_connector.py
- By default it won't show the amenity in geojson.
- To show the amenity add "visible" to true in heatmap_config
Related issues:
- #2016
=> [FEAT] visibility of amenities in geojson is false

app/client-v2/apps/goat/app/(dashboard)/content/ContentManagement.tsx, app/client-v2/apps/goat/app/(dashboard)/content/HeaderCard.tsx, app/client-v2/apps/goat/app/(dashboard)/content/TreeViewFilter.tsx, app/client-v2/apps/goat/app/(dashboard)/home/page.tsx, app/client-v2/apps/goat/app/(dashboard)/layout.tsx, app/client-v2/apps/goat/app/(dashboard)/settings/layout.tsx, app/client-v2/apps/goat/app/(dashboard)/settings/organization/ManageUsers.tsx, app/client-v2/apps/goat/app/(dashboard)/settings/organization/Teams.tsx, app/client-v2/apps/goat/app/(dashboard)/settings/organization/page.tsx, app/client-v2/apps/goat/components/grid/GridContainer.tsx, app/client-v2/apps/goat/components/grid/SingleGrid.tsx, app/client-v2/apps/goat/lib/utils/helpers.ts, app/client-v2/packages/ui/components/Inputs/Autocomplete.tsx, app/client-v2/packages/ui/components/Navigation/Tabs.tsx, app/client-v2/packages/ui/components/Surfaces/Banner.tsx
Made 2 new components for the grid
=> feat: added the grid

app/client-v2/apps/goat/app/(dashboard)/content/page.tsx, app/client-v2/packages/keycloak-theme/src/login/Template.tsx, app/client-v2/packages/keycloak-theme/src/login/pages/RegisterUserProfile.tsx, app/client-v2/packages/ui/components/BasicSnackbar.tsx, app/client-v2/packages/ui/components/MapByLayer.tsx, app/client-v2/packages/ui/components/Navigation/DashboardSidebar.tsx, app/client-v2/packages/ui/components/Navigation/Toolbar.tsx, app/client-v2/packages/ui/components/temporary/contentManagement/ContentManagement.tsx, app/client-v2/packages/ui/components/temporary/contentManagement/components/HeaderCard.tsx, app/client-v2/packages/ui/components/temporary/settings/Settings.tsx, app/client-v2/packages/ui/stories/components/Data Display/Divider.stories.tsx, app/client-v2/packages/ui/stories/components/Inputs/SelectField.stories.tsx, app/client-v2/packages/ui/stories/components/Inputs/TextField.stories.tsx, app/client-v2/packages/ui/stories/components/Navigation/Sidebar.stories.tsx, app/client-v2/packages/ui/stories/components/Snackbar.stories.tsx
https://github.com/orgs/goat-community/projects/1/views/45?pane=issue&itemId=33878837
=> Add snackbar with alert

app/api/src/crud/crud_isochrone.py, app/client/src/store/modules/poisaois.js
=> Merging hotfix

app/client-v2/apps/goat/app/(dashboard)/DashboardSidebar.tsx, app/client-v2/apps/goat/app/(dashboard)/content/ContentManagement.tsx, app/client-v2/apps/goat/app/(dashboard)/content/HeaderCard.tsx, app/client-v2/apps/goat/app/(dashboard)/content/MoreMenu.tsx, app/client-v2/apps/goat/app/(dashboard)/content/ShareModal.tsx, app/client-v2/apps/goat/app/(dashboard)/layout.tsx, app/client-v2/apps/goat/app/(dashboard)/settings/layout.tsx, app/client-v2/apps/goat/app/(dashboard)/settings/organization/AddTeamModal.tsx, app/client-v2/apps/goat/app/(dashboard)/settings/organization/Overview.tsx, app/client-v2/apps/goat/app/(dashboard)/settings/organization/TeamModalBody.tsx, app/client-v2/apps/goat/app/(dashboard)/settings/organization/Teams.tsx, app/client-v2/apps/goat/app/(dashboard)/settings/organization/TeamsTable.tsx, app/client-v2/apps/goat/app/(dashboard)/settings/organization/UserInfoModal.tsx, app/client-v2/apps/goat/app/(dashboard)/settings/organization/page.tsx, app/client-v2/apps/goat/app/(dashboard)/settings/page.tsx, app/client-v2/apps/goat/app/(dashboard)/settings/subscription/SubscriptionSettings.tsx, app/client-v2/apps/goat/app/(dashboard)/settings/subscription/page.tsx, app/client-v2/apps/goat/app/layout.tsx, app/client-v2/apps/goat/app/server/page.tsx, app/client-v2/apps/goat/layouts/Home.tsx, app/client-v2/apps/goat/lib/ThemeRegistry.tsx
[Use absolute paths for all components](https://github.com/goat-community/goat/issues/2456)
https://github.com/orgs/goat-community/projects/1/views/45?pane=issue&itemId=33909851
=> Use absolute paths for all components

app/client-v2/apps/goat/app/(dashboard)/DashboardSidebar.tsx, app/client-v2/apps/goat/middleware.ts, app/client-v2/packages/ui/components/MapByLayer.tsx, app/client-v2/packages/ui/stories/components/Map Components/MapLayers.stories.tsx
[Map show Raster XYZ#2418](https://github.com/goat-community/goat/issues/2418)
=> Implemented XYZ layer

app/api/src/crud/crud_content.py, app/api/src/crud/crud_layer.py, app/api/src/db/models/content.py, app/api/src/db/models/layer.py, app/api/src/endpoints/deps.py, app/api/src/endpoints/helpers.py, app/api/src/endpoints/v2/layers.py, app/api/src/schemas/content.py, app/api/src/schemas/layer.py
=> Layers endpoint

app/api/src/core/heatmap/heatmap_read.py
=> [FIX] heatmap bug

app/api/src/schemas/isochrone.py
=> Hotfix heatmap bug

app/api/src/endpoints/v1/indicators.py
=> [HOTFIX] Heatmap

app/api/src/endpoints/v1/indicators.py, app/api/src/workers/method_connector.py
=> Hotfix Heatmap

app/client/apps/goat/app/[lng]/layout.tsx, app/client/apps/goat/components/styling/StylingMap.tsx, app/client/apps/goat/components/styling/StylingSideBar.tsx, app/client/apps/goat/lib/store/providers/StoreProvider.tsx, app/client/packages/ui/components/DataDisplay/Chip.tsx, app/client/packages/ui/components/DataDisplay/Icon.tsx, app/client/packages/ui/components/DataDisplay/IconButton.tsx, app/client/packages/ui/components/DataDisplay/index.ts, app/client/packages/ui/components/theme.ts
=> Fixing some errors

apps/web/components/builder/widgets/information/Layers.tsx, apps/web/components/map/MapViewer.tsx, apps/web/components/map/panels/Legend.tsx, apps/web/lib/store/map/slice.ts
=> fix: legend
